#!/bin/python3

import math
import os
import random
import re
import sys

class SinglyLinkedListNode:
    def __init__(self, node_data):
        self.data = node_data
        self.next = None

class SinglyLinkedList:
    def __init__(self):
        self.head = None

def print_singly_linked_list(node, sep, fptr):
    while node:
        fptr.write(str(node.data))

        node = node.next

        if node:
            fptr.write(sep)

# Complete the insertNodeAtTail function below.

#
# For your reference:
#
# SinglyLinkedListNode:
#     int data
#     SinglyLinkedListNode next
#
#
def insertNodeAtTail(head, data):
    newNode = SinglyLinkedListNode(data) #Create a new node that you need to insert
    
    if head is None:     #Check if the linkedlist is empty , if empty the newnode will become the head
        head = newNode
        return head
    
    currNode = head      # If the linked list is not empty , start from head (currNode) and navigate untill tail 
    while currNode.next:
        currNode = currNode.next
    currNode.next = newNode      #Assign the tail node to the new node and return the head
    return head

if __name__ == '__main__':
